# Generated by Django 4.2.6 on 2023-11-02 12:04

from django.db import migrations, models
import esign.models


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="pdf_file",
            field=models.FileField(
                default=esign.models.default_pdf_path,
                upload_to="pdfs/",
                validators=[esign.models.validate_pdf_extension],
            ),
        ),
    ]
