# Generated by Django 4.2.6 on 2023-11-14 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0002_document_pdf_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="content",
        ),
    ]
