# Generated by Django 4.2.6 on 2023-11-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0004_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="orgID",
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
