# Generated by Django 4.2.6 on 2023-11-16 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0007_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocPermission",
            fields=[
                (
                    "dpID",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=50)),
                (
                    "docID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="esign.document"
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
