# Generated by Django 4.2.6 on 2023-11-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0008_docpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="docID",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
