# Generated by Django 4.2.6 on 2023-11-16 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0009_document_docid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docpermission",
            name="docID",
        ),
    ]
