# Generated by Django 4.2.6 on 2023-11-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0010_remove_docpermission_docid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="id",
        ),
        migrations.AlterField(
            model_name="document",
            name="docID",
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
