# Generated by Django 4.2.6 on 2023-11-16 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0011_remove_document_id_alter_document_docid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signature",
            old_name="document",
            new_name="docID",
        ),
    ]
