# Generated by Django 4.2.6 on 2023-11-16 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0013_delete_signature"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature", models.ImageField(upload_to="signatures")),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "docID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="esign.document"
                    ),
                ),
            ],
        ),
    ]
