# Generated by Django 4.2.6 on 2023-11-17 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0014_signature"),
    ]

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "urlID",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("url", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "docID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="esign.document"
                    ),
                ),
                (
                    "dpID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="esign.docpermission",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
