# Generated by Django 4.2.6 on 2023-11-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0016_docpermission_docid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docpermission",
            name="docID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="esign.document"
            ),
        ),
    ]
