# Generated by Django 4.2.6 on 2023-11-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0017_alter_docpermission_docid"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
