# Generated by Django 4.2.6 on 2023-11-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0019_alter_document_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
