# Generated by Django 4.2.6 on 2023-11-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0020_document_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
