# Generated by Django 4.2.6 on 2023-11-19 09:34

from django.db import migrations, models
import esign.models


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0022_remove_document_due_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "docID",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "pdf_file",
                    models.FileField(
                        default=esign.models.default_pdf_path,
                        upload_to="pdfs/",
                        validators=[esign.models.validate_pdf_extension],
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
