# Generated by Django 4.2.6 on 2023-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0024_alter_document_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="MFA",
            field=models.BooleanField(default=True),
        ),
    ]
