# Generated by Django 4.2.6 on 2023-11-22 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0025_customuser_mfa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remark",
            fields=[
                (
                    "remarkID",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="esign.document"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
