# Generated by Django 4.2.6 on 2023-11-22 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("esign", "0026_remark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remark",
            old_name="document",
            new_name="docID",
        ),
        migrations.RenameField(
            model_name="remark",
            old_name="user",
            new_name="userID",
        ),
    ]
