# Generated by Django 4.2.7 on 2023-11-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0027_rename_document_remark_docid_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
