# Generated by Django 4.2.7 on 2023-11-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0028_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='orgID',
        ),
    ]
