# Generated by Django 4.2.7 on 2023-12-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0032_alter_customuser_orgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpermission',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
