# Generated by Django 4.2.7 on 2023-12-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0033_docpermission_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
